### ISSUE TITLE
GetBalance api is waiting forever

### ISSUE THREAD

**Issue by adasari** [ava-labs/gecko#186] opened 2020-05-27 03:25 UTC
**Describe the bug**
GetBalance API is not responsive

**To Reproduce**
1. Firewall on (it means incoming traffic on 9651 is blocked). (this is not intentional, i missed to turnoff firewall)
2. Create user and wallet address
3. Add balance in faucet testnet
4. Hit the balance api. it shows balance as zero
5. wait for some time till you see following log in your node.
INFO [05-27|08:13:23] <chain 4ktRjsAKxgMr2aEzv9SWmrU7Xk5FniHUrVCX4P1TZSfTLZWFM> /snow/engine/avalanche/bootstrapper.go#234: bootstrapping finished fetching vertices. executing state transitions...
6. Hit GetBalance api. it waits forever.

**Expected behavior**
API shouldn't wait forever. should return zero.

**Screenshots**

**Operating System**
Ubunut 1804

**Additional context**
Node console outout

```
INFO [05-27|08:07:27] <chain 4ktRjsAKxgMr2aEzv9SWmrU7Xk5FniHUrVCX4P1TZSfTLZWFM> /snow/engine/avalanche/bootstrapper.go#178: bootstrapping has fetched 5000 vertices




INFO [05-27|08:11:06] <chain 4ktRjsAKxgMr2aEzv9SWmrU7Xk5FniHUrVCX4P1TZSfTLZWFM> /snow/engine/avalanche/bootstrapper.go#178: bootstrapping has fetched 7500 vertices
INFO [05-27|08:13:23] <chain 4ktRjsAKxgMr2aEzv9SWmrU7Xk5FniHUrVCX4P1TZSfTLZWFM> /snow/engine/avalanche/bootstrapper.go#234: bootstrapping finished fetching vertices. executing state transitions...



INFO [05-27|08:13:23] <chain 4ktRjsAKxgMr2aEzv9SWmrU7Xk5FniHUrVCX4P1TZSfTLZWFM> /snow/engine/avalanche/bootstrapper.go#234: bootstrapping finished fetching vertices. executing state transitions...

<.... turned off firewall.....>
ERROR[05-27|08:17:38] <chain 4ktRjsAKxgMr2aEzv9SWmrU7Xk5FniHUrVCX4P1TZSfTLZWFM> /vms/avm/unique_tx.go#126: Failed to fund utxo %!s(uint64=1) due to packer has insufficient length for input
INFO [05-27|08:17:44] <chain 4ktRjsAKxgMr2aEzv9SWmrU7Xk5FniHUrVCX4P1TZSfTLZWFM> /snow/engine/avalanche/transitive.go#66: Bootstrapping finished with 2 vertices in the accepted frontier
INFO [05-27|08:17:46] <chain 11111111111111111111111111111111LpoYY> /vms/platformvm/vm.go#697: next scheduled event is at 2020-05-27 17:46:05 +0530 IST (9h28m18.727995s in the future)
INFO [05-27|08:17:46] <chain 11111111111111111111111111111111LpoYY> /vms/platformvm/vm.go#697: next scheduled event is at 2020-05-27 17:46:05 +0530 IST (9h28m18.7192507s in the future)
```

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by joesixpack** [comment] 2020-05-27 03:33
Having this problem too after sync.

**Comment by peterphan1996** [comment] 2020-06-18 09:05
I'm having this problem too on 0.5.5

**Comment by danlaine** [comment] 2020-06-24 19:36
Hi all, can you please see if you still have this issue when running with version 0.5.7?
Let me know. Thanks

**Comment by danlaine** [comment] 2020-06-24 19:36
(oops didn't mean to close this just yet)

**Comment by adasari** [comment] 2020-06-25 19:44
sure. will test.

**Comment by adasari** [comment] 2020-06-25 21:27
GetBalance api is still waits forever when X-chain is executing operations

See following logs when GetBalance api is hit

```
INFO [06-26|02:55:47] <X Chain> /snow/engine/avalanche/bootstrapper.go#330: executed 890000 operations
INFO [06-26|02:55:50] <X Chain> /snow/engine/avalanche/bootstrapper.go#330: executed 892500 operations
INFO [06-26|02:55:52] <X Chain> /snow/engine/avalanche/bootstrapper.go#330: executed 895000 operations
INFO [06-26|02:55:55] <X Chain> /snow/engine/avalanche/bootstrapper.go#330: executed 897500 operations
INFO [06-26|02:55:57] <X Chain> /snow/engine/avalanche/bootstrapper.go#330: executed 900000 operations
```

**Comment by adasari** [comment] 2020-06-25 21:58
once X-chain bootstrapping is completed, GetBalance api is returning response.

**Comment by adasari** [comment] 2020-06-25 22:07
Infinite waits are incorrect. i looked at the code and should use contexts here to set the timeouts in future if required ? thoughts ?

**Comment by danlaine** [comment] 2020-06-25 22:12
@adasari The expected behavior right now is that if bootstrapping is not completed, an API call may hang forever. As such, I'm going to close this issue since your call completed after finishing bootstrapping. However, you're totally right that we should use contexts and timeouts. I'll leave this for a separate feature request issue, though. Thanks for the suggestion :)

**Closed by danlaine** 2020-06-25 22:12 UTC
Labels: bug
