### ISSUE TITLE
Gecko does not respond to the standard SIGTERM signal (kill 15 or CTRL+C)

### ISSUE THREAD

**Issue by k0kk0k** [ava-labs/gecko#89] opened 2020-04-21 10:21 UTC
**Describe the bug**
The `ava` node process does not respond to the SIGTERM signal, and the process can only be stopped with a SIGKILL signal (kill 9)

**Operating System**
UBUNTU 18.04

**Reproduce**

`screen`
`./ava`
try to interrupt: press `ctrl+c`

**Result (piece of the output log)**
```2020-04-21 12:12:31.772889 [net info] <Conn fd=66 addr=<NetAddr 78.168.90.52:9651> mode=active> connect timeout
2020-04-21 12:12:31.773010 [net info] <Conn fd=76 addr=<NetAddr 95.179.163.191:9801> mode=active> connect timeout
2020-04-21 12:12:31.773060 [net info] 04ea443790: lost connection <Conn fd=66 addr=<NetAddr 78.168.90.52:9651> mode=active>
2020-04-21 12:12:31.773112 [net info] 04ea443790: lost connection <Conn fd=76 addr=<NetAddr 95.179.163.191:9801> mode=active>
ERROR[04-21|12:12:31] /node/node.go#140: Error during async call: unable to connect
ERROR[04-21|12:12:31] /node/node.go#140: Error during async call: unable to connect
^CINFO [04-21|12:12:33] /node/node.go#652: shutting down the node
INFO [04-21|12:12:33] <chain 11111111111111111111111111111111LpoYY> /snow/engine/snowman/transitive.go#56: Shutting down Snowman consensus
^C^C^C^C^C^C^C^C^C2020-04-21 12:15:26.462926 [net info] 04ea443790: peer ping-pong timeout
2020-04-21 12:15:26.463102 [net info] 04ea443790: peer ping-pong timeout
2020-04-21 12:15:26.463442 [net info] 04ea443790: lost connection <Conn fd=31 addr=<NetAddr 18.234.153.22:21001> mode=active>
2020-04-21 12:15:26.463514 [net info] 04ea443790: lost connection <Conn fd=37 addr=<NetAddr 34.207.133.167:21001> mode=active>
2020-04-21 12:15:26.509655 [net info] 04ea443790: peer ping-pong timeout
2020-04-21 12:15:26.509730 [net info] 04ea443790: peer ping-pong timeout
2020-04-21 12:15:26.509758 [net info] 04ea443790: peer ping-pong timeout
2020-04-21 12:15:26.509772 [net info] 04ea443790: peer ping-pong timeout
```
![image](https://user-images.githubusercontent.com/60854664/79854924-e8c7cb00-83d2-11ea-8813-c8fe5fd4a6a0.png)

**Comment by danlaine** [comment] 2020-04-22 15:20
@k0kk0k Hey, thanks for the bug report. We're looking into this.

**Comment by StephenButtolph** [comment] 2020-05-13 02:49
I think this is a duplicate of #66. If you run into this error again please reopen this issue. Thanks for bringing this up!

**Comment by danlaine** [comment] 2020-05-14 20:27
@moreati Reported that ctrl+C is not killing a node on revision f290f7377.
Output:
```
2020-05-14 21:17:31.202558 [net info] f1aa88b4b5: lost connection <Conn fd=78 addr=<NetAddr 167.86.111.215:9651> mode=active>
^CINFO [05-14|21:17:31] /node/node.go#664: shutting down the node
INFO [05-14|21:17:31] <chain 2kKSkL4vgVR6QSknoKprsGHVHiEbf7WiGEeSuJUGoB3WzeBhce> /snow/engine/snowman/transitive.go#110: Shutting down Snowman consensus
2020-05-14T21:17:31.436+0100 [TRACE] plugin.sh: plugin received interrupt signal, ignoring: count=1 timestamp=2020-05-14T21:17:31.436+0100
INFO [05-14|21:17:31] <chain 11111111111111111111111111111111LpoYY> /snow/engine/snowman/transitive.go#110: Shutting down Snowman consensus
2020-05-14 21:17:32.122074 [net info] created <Conn fd=78 addr=<NetAddr 62.171.140.121:9651> mode=active>
2020-05-14 21:17:32.218771 [net info] connected to remote <Conn fd=78 addr=<NetAddr 62.171.140.121:9651> mode=active>
2020-05-14 21:17:32.303968 [net info] f1aa88b4b5: setup connection <Conn fd=78 addr=<NetAddr 62.171.140.121:9651> mode=active>
2020-05-14 21:17:32.402516 [net info] created <Conn fd=87 addr=<NetAddr 167.86.111.215:9651> mode=active>
2020-05-14 21:17:32.473000 [net info] connected to remote <Conn fd=87 addr=<NetAddr 167.86.111.215:9651> mode=active>
2020-05-14 21:17:32.540595 [net info] f1aa88b4b5: setup connection <Conn fd=87 addr=<NetAddr 167.86.111.215:9651> mode=active>
^C2020-05-14T21:17:32.652+0100 [TRACE] plugin.sh: plugin received interrupt signal, ignoring: count=2 timestamp=2020-05-14T21:17:32.652+0100
2020-05-14 21:17:33.543559 [net info] created <Conn fd=79 addr=<NetAddr 167.86.111.215:9651> mode=active>
...
```

**Comment by moreati** [comment] 2020-05-14 20:36
Same with rev 7c4abdea66af9187a5921a3c2d166b3cffc8aabf.

Ubuntu 20.04 x64, go version go1.13.8 linux/amd64 (from distro packages)

**Closed** 2020-05-31 23:38 UTC
Labels: bug
