### ISSUE TITLE
Sending Fixed asset error

### ISSUE THREAD

**Issue by slideloft** [ava-labs/gecko#150] opened 2020-05-09 21:19 UTC
**Describe the bug**
I tried sending a fixed asset i created to another wallet but it throws up `{"jsonrpc":"2.0","error":{"code":-32000,"message":"insufficient funds","data":null},"id":3}`
**To Reproduce**
After creating fixed asset , i tried 
```
curl -X POST --data '{
    "jsonrpc":"2.0",
    "id"     :3,
    "method" :"avm.send",
    "params" :{
        "username":"myusername",
        "password":"mypassword",
        "assetID" :"ZKa9mB1SfMBX9AaX5ZwjCmw6UHFffaFfFJjyJ5bzSKBnjrMsG",
        "amount"  :100,
        "to"      :"X-9BkroVVgakMP88Dp7nyu3PQyYhpNgig6p"
    }
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/X

```

**Expected behavior**
It should have sent the fixed asset to the wallet address in "to"

**Screenshots**
[Screenshot](https://imgur.com/a/Q6qI0tg)
**Operating System**
OS: Ubuntu == 18.04 

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment] 2020-05-12 12:56
Hi @slideloft are you sure that the specified user controlled 100 units of the specified asset? Are you able to reproduce this bug?

**Comment by el33th4x0r** [comment] 2020-05-12 13:04
Is it possible that there's some confusion due to the number of decimal
places? Perhaps he created far fewer assets than he thought.  Is the
documentation crystal clear about how fractionalizable assets work?

**Comment by danlaine** [comment] 2020-05-12 13:13
@el33th4x0r It's really hard to say what the problem here is without more context.
I don't think it has to do with asset fractionalization.
The docs on asset creation are [here](https://docs.ava.network/v1.0/en/tutorials/fixed-cap-asset/).

**Comment by spvyerra** [comment] 2020-05-12 18:15
I am having a similar issue actually doing this using the slopes library.
This is how I am declaring my Fixed cap asset.

```
let assetId = await avm.createFixedCapAsset(
        "username",
        "password",
        "Fixed Asset Attempt 2",
        "THT", [
        { "address": acct1, amount: 1000 },
        { "address": acct2, amount: 2000 },
    ]);
```

And then I am trying to send some of the asset I created from acct2 to a different address.

```
let txId = await avm.send("username", "password", assetId, 100, acct3);
```

Both Accounts have AVA on them so I do not believe that is an issue. Using `avm.getBalance(address, "AVA")`
The avm.send command is where I am getting the error.

`{"jsonrpc":"2.0","error":{"code":-32000,"message":"insufficient funds","data":null},"id":2}`

**Comment by StephenButtolph** [comment] 2020-05-13 05:23
I just ran through a full pass of this workflow with a fresh account. I'll list out the steps I took.

First, I'll create a brand new keystore user for this asset.
```
curl --location --request POST 'http://localhost:9650/ext/keystore' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "keystore.createUser",
    "params":{
    	"username":"username",
    	"password":"qwertyuiopasdfghjklzxcvbnm"

    },
    "id": 84
}'
```

Creation of that user should have been successful as long as it hadn't already been created.
```
{
    "jsonrpc": "2.0",
    "result": {
        "success": true
    },
    "id": 84
}
```

I'm going to import the first key to my account.
```
curl --location --request POST 'localhost:9650/ext/bc/X' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc":"2.0",
    "id"     :3,
    "method" :"avm.importKey",
    "params" :{
        "username":"username",
        "password":"qwertyuiopasdfghjklzxcvbnm",
        "privateKey":"2AoLETENShi5f9gsgbyFpmDDiRfBvThjCcs8RU8ESrHrMkU986"
    }
}'
```

Importing this key should always succeed and gives me the keys address.
```
{
    "jsonrpc": "2.0",
    "result": {
        "address": "X-2nVk8hMg5PhGf5Xuu8PhxaRkCKgpgrfXQ"
    },
    "id": 3
}
```

To stay in line with the above issue, I'll import a second key.
```
curl --location --request POST 'localhost:9650/ext/bc/X' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc":"2.0",
    "id"     :4,
    "method" :"avm.importKey",
    "params" :{
        "username":"username",
        "password":"qwertyuiopasdfghjklzxcvbnm",
        "privateKey":"2a2x6ARFk1pfpuwcwWyX6pXgFJWujLzGuKFDa8ee88CLfceXaj"
    }
}'
```

Which also should always succeed and return the address.
```
{
    "jsonrpc": "2.0",
    "result": {
        "address": "X-NNz6zch3ajCmrHH3XHzM1nujUSkv6jjoT"
    },
    "id": 4
}
```

Now I'm going to make the asset, similarly to how you said your asset was made.
```
curl --location --request POST 'localhost:9650/ext/bc/X' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc":"2.0",
    "id"     : 1,
    "method" :"avm.createFixedCapAsset",
    "params" :{
        "name": "Fixed Asset Attempt 3",
        "symbol":"FAA",
        "initialHolders": [
            {
                "address":"X-2nVk8hMg5PhGf5Xuu8PhxaRkCKgpgrfXQ",
                "amount":1000
            },
            {
                "address":"X-NNz6zch3ajCmrHH3XHzM1nujUSkv6jjoT",
                "amount":2000
            }
        ],
        "username":"username",
        "password":"qwertyuiopasdfghjklzxcvbnm"
    }
}'
```

This creation returns the assetID of the newly issued asset.
```
{
    "jsonrpc": "2.0",
    "result": {
        "assetID": "29idxJfsmsowWN2omdVHtBEQhEREnepft4VHtwZZj5zQjANbpj"
    },
    "id": 1
}
```

We can now check the balance on the first address.
```
curl --location --request POST 'http://localhost:9650/ext/bc/X' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc":"2.0",
    "id"     :2,
    "method" :"avm.getBalance",
    "params" :{
        "address":"X-2nVk8hMg5PhGf5Xuu8PhxaRkCKgpgrfXQ",
        "assetID":"29idxJfsmsowWN2omdVHtBEQhEREnepft4VHtwZZj5zQjANbpj"
    }
}'
```

The first address had 1000 allocated.
```
{
    "jsonrpc": "2.0",
    "result": {
        "balance": "1000",
        "utxoIDs": [
            {
                "txID": "29idxJfsmsowWN2omdVHtBEQhEREnepft4VHtwZZj5zQjANbpj",
                "outputIndex": 0
            }
        ]
    },
    "id": 2
}
```

Similarly for the second address.
```
curl --location --request POST 'http://localhost:9650/ext/bc/X' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc":"2.0",
    "id"     :2,
    "method" :"avm.getBalance",
    "params" :{
        "address":"X-NNz6zch3ajCmrHH3XHzM1nujUSkv6jjoT",
        "assetID":"29idxJfsmsowWN2omdVHtBEQhEREnepft4VHtwZZj5zQjANbpj"
    }
}'
```

This address had twice as much allocated.
```
{
    "jsonrpc": "2.0",
    "result": {
        "balance": "2000",
        "utxoIDs": [
            {
                "txID": "29idxJfsmsowWN2omdVHtBEQhEREnepft4VHtwZZj5zQjANbpj",
                "outputIndex": 1
            }
        ]
    },
    "id": 2
}
```

We can now send some of the asset to a third address.
```
curl --location --request POST 'http://localhost:9650/ext/bc/avm' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc":"2.0",
    "id"     :3,
    "method" :"avm.send",
    "params" :{
        "username":"username",
        "password":"qwertyuiopasdfghjklzxcvbnm",
        "assetID":"29idxJfsmsowWN2omdVHtBEQhEREnepft4VHtwZZj5zQjANbpj",
        "amount":1,
        "to":"X-HA2XXDb13xwSZE9wErsyU1N5rvPXDT2fF"
    }
}'
```

Which returns the transaction ID.
```
{
    "jsonrpc": "2.0",
    "result": {
        "txID": "2vYC1s3CvceoqsXFxTgnnDwpMLWXuYEY4V52QyBFe7XCZa1553"
    },
    "id": 3
}
```

I can now check the balance of this third address.
```
curl --location --request POST 'http://localhost:9650/ext/bc/X' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc":"2.0",
    "id"     :2,
    "method" :"avm.getBalance",
    "params" :{
        "address":"X-HA2XXDb13xwSZE9wErsyU1N5rvPXDT2fF",
        "assetID":"29idxJfsmsowWN2omdVHtBEQhEREnepft4VHtwZZj5zQjANbpj"
    }
}'
```

Which now has one of the tokens that were newly created.
```
{
    "jsonrpc": "2.0",
    "result": {
        "balance": "1",
        "utxoIDs": [
            {
                "txID": "2vYC1s3CvceoqsXFxTgnnDwpMLWXuYEY4V52QyBFe7XCZa1553",
                "outputIndex": 0
            }
        ]
    },
    "id": 2
}
```

What was the first step in this process that failed when you tried it?

**Comment by slideloft** [comment] 2020-05-13 09:03
> Hi @slideloft are you sure that the specified user controlled 100 units of the specified asset? Are you able to reproduce this bug?

the asset wallet : https://explorer.ava.network/address/Dxs8JWAzDZX1VXcLZT5GZR7TyfX8h9ic9
Asset ID : https://explorer.ava.network/tx/ZKa9mB1SfMBX9AaX5ZwjCmw6UHFffaFfFJjyJ5bzSKBnjrMsG

**Comment by slideloft** [comment] 2020-05-13 09:04
> @el33th4x0r It's really hard to say what the problem here is without more context.
> I don't think it has to do with asset fractionalization.
> The docs on asset creation are [here](https://docs.ava.network/v1.0/en/tutorials/fixed-cap-asset/).

i used the doc : https://docs.ava.network/v1.0/en/tutorials/fixed-cap-asset/

**Comment by slideloft** [comment] 2020-05-13 09:12
I tried tracking the time i ran into the error and it may have been when the testnet was unstable. It corresponded with the testnet offline of May 8,
I later created a different instance and was able to create a token .
It could be or may not be the offline cause, probably do a community task to test this function.

**Comment by danlaine** [comment] 2020-05-13 12:56
@slideloft Were you able to send the new token you created? Any problems?

**Comment by slideloft** [comment] 2020-05-13 13:23
> @slideloft Were you able to send the new token you created? Any problems?

Yes the new token i created works okay : FIAT

**Comment by danlaine** [comment] 2020-05-13 13:32
@slideloft Great! Going to close this issue, then. Let us know if you run into any other issues.

**Closed by danlaine** 2020-05-13 13:32 UTC
Labels: bug
