### ISSUE TITLE
Wrong status of double spending transactions

### ISSUE THREAD

**Issue by ekherit** [ava-labs/gecko#263] opened 2020-06-29 13:29 UTC
**Describe the bug**
There are wrong status when I am sending several  (one by one without confirmation) transactions from same address.

**To Reproduce**
Gecko 0.5.7
Let send 5 transaction from address  'X-CsEZoWbBXLqCmjt8gdLSFyHKxCZw8gQQx' (alisa) to X-BZUz5nMxahio79tzdxnYKsV3uS8o1gXDn (bob) one by one without waiting confirmation. Every transaction is 1nAVA
Then check the status of each transaction every second and wait confirmation. The output of my script is on screenshot.
You will see that alisa's balance decreases on 2 nAVA and bob's balance increase on 2 nAVA. And probaly that is OK.
But between count 1 and count 2 there are status of these 5 transacations checked every 1 second. And all 5 transactions
have status 'Accepted'

**Expected behavior**
There are two options:

1. Accept all 5 transactions and balance must be changed on 5 nAVA. Then all 5 transaction will have Accepted status. It would
happen if when I am sending last transaction the first one already change UTXO. But this is strange, status is not accepted. 

2.  Reject 3 transactions and accept only 2 transaction. 

P.S. I have 4 UTXO on alisa's adress. So sometimes balance changes on 4 nAVA. But still one transaction must be rejected.

**Screenshots**
![a](https://user-images.githubusercontent.com/2533826/86008935-b75b2380-ba43-11ea-98eb-e4d4ad293b2e.png)

**Operating System**
Debian testing

**Additional context**
Gecko 0.5.7
Python script:
https://github.com/ekherit/pyava/blob/master/ping_pong.py

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment] 2020-06-29 13:42
@ekherit Hi, thanks for taking the time to make this :)
I think what's happening is that you are not actually issuing 5 transactions. If you call `send`, and then call `send` again before the previous transaction is done processing, it will generate the same transaction because the UTXO set hasn't yet changed.

Are you sure that each of these 5 transactions are not actually the same transaction?

**Comment by ekherit** [comment] 2020-06-29 14:21
Hi, @danlaine  
Thank you for your fast answer.

I have checked transaction's Id, they were different.  When I wanted to show you the txid's I did a mistake and send avas from bob to alisa due to name swap in my script.  This result in  too many UTXO in alisa's address.  When I try to make only single UTXO I have found that I cant move all funds from bob's address to alisa because there are so many input UTXO for such transactions. 
Exception: ('error', {'code': -32000, 'message': 'problem creating transaction: packer has insufficient length for input', 'data': None})

So this is bug or feature and  I don't have much time to fight with this, so I will check carefully the txids and it's UTXO later.

**Comment by danlaine** [comment] 2020-06-29 14:25
@ekherit I'm not 100% sure I understand what you said about too many UTXOs. Can you elaborate.

Can you also elaborate on how you are getting this `packer has insufficient length for input` error? 

Thanks!

**Comment by ekherit** [comment] 2020-06-30 06:26
@danlaine 
I was testing the transaction speed by sending 1 nAVA many times. Thus there are more then 20000 UTXO at  address "X-BZUz5nMxahio79tzdxnYKsV3uS8o1gXDn":
 curl -X POST --data '{
  "jsonrpc":"2.0",
  "id"     : 1,
  "method" :"avm.getBalance",
  "params" :{
      "address":"X-BZUz5nMxahio79tzdxnYKsV3uS8o1gXDn",
      "assetID": "AVA"
  }
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/X 
Too much output here to show...

When I am sending all amount to some address
curl -X POST --data '{
    "jsonrpc":"2.0",
    "id"     :1,
    "method" :"avm.send",
    "params" :{
        "assetID" :"AVA",
        "amount"  :77994,
        "to"      :"X-CsEZoWbBXLqCmjt8gdLSFyHKxCZw8gQQx",
        "username":"alisa",
        "password":"<my_pass>"
    }
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/X
Result  is  error:
{"jsonrpc":"2.0","error":{"code":-32000,"message":"problem creating transaction: packer has insufficient length for input","data":null},"id":1}
It seems to be packer unable to gather 20k utxo together  due to some buffer limit.

**Comment by ekherit** [comment] 2020-06-30 06:50
@danlaine 
How to send you private key for address "X-BZUz5nMxahio79tzdxnYKsV3uS8o1gXDn" privately ?

**Comment by ekherit** [comment] 2020-06-30 07:06
@danlaine
You was right about same transaction. I created address with only one UTXO and find out that all sending txids are the same. Sorry
for my fault.  Shoud I close the bug, or we can discuss  insufficient length for input  here?

**Comment by danlaine** [comment] 2020-06-30 12:46
@ekherit If you want to send me something private, you can message me on Discord (@danlaine)

Let's close this issue, and can you please create a new issue for the `insufficient length` problem you're seeing, including how to reproduce it? Thanks for your help!

**Closed by danlaine** 2020-06-30 12:46 UTC
Labels: bug
