### ISSUE TITLE
High CPU usage on low-end x86 hardware

### ISSUE THREAD

**Issue by mbehrsf** [ava-labs/gecko#282] opened 2020-07-11 11:24 UTC
**Describe the bug**
CPU usage of my validator node is constantly >100%, load avg ranges from 3-4. My hardware is low-end, but since people are using Raspberry Pis, I figured it should be strong enough to run a validator. I am getting higher benchmark scores using Geekbench 5 than the Raspberry Pi 4: https://browser.geekbench.com/v5/cpu/compare/2823854?baseline=2881214 . 

If I copy the entire ~/.gecko/ folder to a VM on my powerful desktop PC, gecko runs fine with just ~2% CPU usage.
 
**To Reproduce**
Build the latest version of gecko from source (634a4d0ee54e579cd48702ef3665b2c5608f1dc3). Bootstrap and add the node as a validator. Monitor CPU usage with top. Rebooting or restarting gecko doesn't change anything to the situation.

Bootstrapping is definitely done: {"jsonrpc":"2.0","result":{"isBootstrapped":true},"id":1}

**Expected behavior**
Once bootstrapping is done, I expect CPU usage <100% as reported by multiple RPi users.

**Operating System**
Ubuntu Server 20.04 64 bit. Intel N3160 CPU with 8 GB RAM. Beefy cooling system installed so the CPU runs at the turbo clock speed of 2.24 GHz almost constantly at roughly 55°C.

**Additional context**
I am adding a CPU profile file.
[cpu.profile.zip](https://github.com/ava-labs/gecko/files/4906642/cpu.profile.zip)

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by mbehrsf** [comment] 2020-07-11 11:29
I am also adding a sample of my top output:

Tasks: 125 total,   2 running, 123 sleeping,   0 stopped,   0 zombie
%Cpu(s): 85.3 us, 14.7 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   7883.4 total,   1444.4 free,   2660.3 used,   3778.6 buff/cache
MiB Swap:   4096.0 total,   4096.0 free,      0.0 used.   6160.9 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                              
   1510 cj        20   0 3627204   2.3g  20152 S 343.8  30.1   2233:02 ava                                                                  
    138 root      20   0       0      0      0 R  37.5   0.0   3:10.98 kworker/1:1+events                                                   
   6230 cj        20   0    8044   3772   3156 R   6.2   0.0   0:00.02 top                                                                  
      1 root      20   0  167696  11772   8616 S   0.0   0.1   0:02.86 systemd                                                              
      2 root      20   0       0      0      0 S   0.0   0.0   0:00.02 kthreadd                                                             
      3 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 rcu_gp                                                               
      4 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 rcu_par_gp                                                           
      6 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kworker/0:0H-events_highpri                                          
      9 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 mm_percpu_wq                                                         
     10 root      20   0       0      0      0 S   0.0   0.0   0:01.02 ksoftirqd/0                                                          
     11 root      20   0       0      0      0 I   0.0   0.0   1:22.68 rcu_sched                                                            
     12 root      rt   0       0      0      0 S   0.0   0.0   0:00.21 migration/0                                                          
     13 root     -51   0       0      0      0 S   0.0   0.0   0:00.00 idle_inject/0                                                        
     14 root      20   0       0      0      0 S   0.0   0.0   0:00.00 cpuhp/0                                                              
     15 root      20   0       0      0      0 S   0.0   0.0   0:00.00 cpuhp/1                                                              
     16 root     -51   0       0      0      0 S   0.0   0.0   0:00.00 idle_inject/1                                                        
     17 root      rt   0       0      0      0 S   0.0   0.0   0:00.42 migration/1                                                          
     18 root      20   0       0      0      0 S   0.0   0.0   0:03.71 ksoftirqd/1                                                          
     19 root      20   0       0      0      0 D   0.0   0.0   3:05.16 kworker/1:0+events                                                   
     20 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kworker/1:0H-kblockd                                                 
     21 root      20   0       0      0      0 S   0.0   0.0   0:00.00 cpuhp/2                                                              
     22 root     -51   0       0      0      0 S   0.0   0.0   0:00.00 idle_inject/2                                                        
     23 root      rt   0       0      0      0 S   0.0   0.0   0:00.46 migration/2                                                          
     24 root      20   0       0      0      0 S   0.0   0.0   0:02.34 ksoftirqd/2                                                          
     26 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kworker/2:0H-events_highpri                                          
     27 root      20   0       0      0      0 S   0.0   0.0   0:00.00 cpuhp/3                                                              
     28 root     -51   0       0      0      0 S   0.0   0.0   0:00.00 idle_inject/3                                                        
     29 root      rt   0       0      0      0 S   0.0   0.0   0:00.47 migration/3                                                          
     30 root      20   0       0      0      0 S   0.0   0.0   0:10.98 ksoftirqd/3                                                          
     32 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kworker/3:0H-kblockd                                                 
     33 root      20   0       0      0      0 S   0.0   0.0   0:00.01 kdevtmpfs                                                            
     34 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 netns                                                                
     35 root      20   0       0      0      0 S   0.0   0.0   0:00.00 rcu_tasks_kthre                                                      
     36 root      20   0       0      0      0 S   0.0   0.0   0:00.00 kauditd                                                              
     37 root      20   0       0      0      0 S   0.0   0.0   0:00.03 khungtaskd                                                           
     38 root      20   0       0      0      0 S   0.0   0.0   0:00.00 oom_reaper                                                           
     39 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 writeback                                                            
     40 root      20   0       0      0      0 S   0.0   0.0   0:00.00 kcompactd0                                                           
     41 root      25   5       0      0      0 S   0.0   0.0   0:00.00 ksmd                                                                 
     42 root      39  19       0      0      0 S   0.0   0.0   0:03.18 khugepaged                                                           
    135 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kintegrityd                                                          
    136 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kblockd                                                              
    137 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 blkcg_punt_bio                                                       
    139 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 tpm_dev_wq                                                           
    140 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 ata_sff                                                              
    141 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 md                                                                   
    142 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 edac-poller                                                          
    143 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 devfreq_wq                                                           
    144 root      rt   0       0      0      0 S   0.0   0.0   0:00.00 watchdogd                                                            
    148 root      20   0       0      0      0 S   0.0   0.0   0:00.00 kswapd0                                                              
    149 root      20   0       0      0      0 S   0.0   0.0   0:00.00 ecryptfs-kthrea                                                      
    152 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kthrotld                                                             
    153 root     -51   0       0      0      0 S   0.0   0.0   0:00.00 irq/115-pciehp                                                       
    154 root     -51   0       0      0      0 S   0.0   0.0   0:00.00 irq/116-pciehp                                                       
    155 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 acpi_thermal_pm                                                      
    156 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 vfio-irqfd-clea                                                      
    158 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 ipv6_addrconf                                                        
    169 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kstrp                                                                
    173 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kworker/u9:0                                                         
    190 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 charger_manager                                                      
    239 root      20   0       0      0      0 S   0.0   0.0   0:00.00 scsi_eh_0                                                            
    240 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 scsi_tmf_0                                                           
    241 root      20   0       0      0      0 S   0.0   0.0   0:00.00 scsi_eh_1                                                            
    242 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 scsi_tmf_1                                                           
    244 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 cryptd                                                               
    286 root       0 -20       0      0      0 I   0.0   0.0   0:01.49 kworker/2:1H-kblockd                                                 
    294 root       0 -20       0      0      0 I   0.0   0.0   0:00.36 kworker/1:1H-kblockd                                                 
    295 root       0 -20       0      0      0 I   0.0   0.0   0:01.42 kworker/0:1H-kblockd                                                 
    303 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kdmflush

**Comment by aaronbuchwald** [comment] 2020-07-14 00:21
Thanks for reporting this. We are working on some optimizations to reduce load as well as a fix for a bug that can cause CPU usage to get very high and stay very high for a long period of time. If your node is still running, would you mind attaching a CPU profile of the node, so that we can make sure to address the root cause? The docs to get a CPU profile from the node are here: https://docs.avax.network/v1.0/en/api/admin/#adminstartcpuprofiler

**Comment by mbehrsf** [comment] 2020-07-14 11:42
Thanks for looking into it. I already included a cpu profile in the original post.

**Comment by aaronbuchwald** [comment] 2020-07-14 13:00
From the CPU profile, it looks like it's spending an unordinary amount of time upgrading its TLS connections. How is the wifi on your RPi? Is it possible that it's disconnecting/reconnecting to peers at a high rate?

**Comment by danlaine** [comment] 2020-07-14 13:01
Hi @mbehrsf thanks for reporting. If you run with `--log-level=debug` does it look like your node is constantly connecting to / disconnecting from peers? 

You mentioned copying the entire `~/.gecko` folder to another machine...by any chance are you simultaneously running two nodes with the same staking key (ie same node ID)? You can check the node's ID with:
```
curl --location --request POST 'localhost:9650/ext/info' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "info.getNodeID",
    "params":{},
    "id": 1
}'
```

**Comment by mbehrsf** [comment] 2020-07-14 13:16
> From the CPU profile, it looks like it's spending an unordinary amount of time upgrading its TLS connections. How is the wifi on your RPi? Is it possible that it's disconnecting/reconnecting to peers at a high rate?

I am not using Wifi, using an Ethernet connection directly to my AVM Fritz Box router.

> You mentioned copying the entire `~/.gecko` folder to another machine...by any chance are you simultaneously running two nodes with the same staking key (ie same node ID)? You can check the node's ID 

No, I have never been running the two nodes in parallel, always shut down one node before I launched the other.

Here is a log. I left the process run with --log-level=debug for a few minutes, then shut it down with CTRL+C.

[avalog.zip](https://github.com/ava-labs/gecko/files/4919024/avalog.zip)

**Comment by aaronbuchwald** [comment] 2020-07-14 13:28
Did the run that you just sent the logs for replicate the high CPU usage?

**Comment by mbehrsf** [comment] 2020-07-14 13:30
> Did the run that you just sent the logs for replicate the high CPU usage?

Yes, CPU usage was just as high as before.

**Comment by mbehrsf** [comment] 2020-07-18 08:58
I have tried moving the ~/.gecko/ folder to a different place and started over from scratch. This time with bootstrapping directly on the node instead of my desktop pc. Bootstrapping took ~36h. Once it was done, CPU usage went to around 10-20%. Then I stopped the node and replaced ~/.gecko/staking/ with the backed up version from my previous install. After starting the node, high CPU usage returned. I then replaced ~/.gecko/staking/ with the newly created version again and CPU usage went back down.

After that, I added the new node id as a validator and high CPU usage immediately returned. So it seems the high CPU usage is only there once I am a validator.

Could my CPU just be too slow? I really figured it should work since RPis do...

**Comment by mbehrsf** [comment] 2020-07-26 12:02
Okay, so somehow I just left the node running for a few days without checking and now the CPU usage is suddenly fine, around 2-5% with a load average of less than 0.1. My node is still on the list of current validators. I have now idea what happened as I did not log in to the machine or change any other settings.

**Comment by mbehrsf** [comment] 2020-07-31 09:09
Aaand it's back up to 200%+. Probably just went down during a period of low activity on the networK?

**Comment by danlaine** [comment] 2020-09-08 22:08
@mbehrsf Have you had this issue on version 0.7.0?

**Comment by mbehrsf** [comment] 2020-09-09 08:00
> @mbehrsf Have you had this issue on version 0.7.0?

No, looks like it has been fixed!

**Comment by danlaine** [comment] 2020-09-09 13:07
Great, going to close this issue then. Thanks for reporting and let us know if you have any other issues.

**Closed by danlaine** 2020-09-09 13:07 UTC
Labels: bug
